name: karman
channels:
- conda-forge
- pytorch
dependencies:
- cartopy>=0.21.1
- matplotlib>=3.3.3
- sphinx>=3.4.3
- sphinx_rtd_theme>=0.5.1
- tqdm>=4.56.0
- pytest>=6.2.1
- python>=3.8
- pytorch>=1.9
- numpy>=1.19.5
- pyfiglet>=0.8
- termcolor>=2.3.0
